<?php
$clients = array(
	array(
		"id" => 7,
		"id_user_id" => 2,
		"categorie_client" => "Particulier",
		"adresse_livraison_client" => "1 rue des tests",
		"cp_livraison_client" => "12345",
		"ville_livraison_client" => "TEST",
		"adresse_facture_client" => "1 rue des tests",
		"cp_facture_client" => "12345",
		"ville_facture_client" => "TEST",
		"mode_paiement_client" => "CB",
		"reduction_client" => 0,
		"coefficient_client" => 0,
		"numero_siret_client" => NULL,
		"nom_client" => "Teste",
		"prenom_client" => "Tesse",
		"nom_entreprise_client" => NULL,
	),
	array(
		"id" => 1,
		"categorie_client" => "Particulier",
		"adresse_livraison_client" => "39193 Lulu Way Apt. 696",
		"cp_livraison_client" => "80287 ",
		"ville_livraison_client" => "Baton Rouge",
		"adresse_facture_client" => "39193 Lulu Way Apt. 696",
		"cp_facture_client" => "80287 ",
		"ville_facture_client" => "Baton Rouge",
		"mode_paiement_client" => "CB",
		"reduction_client" => 1,
		"coefficient_client" => 0.00,
		"numero_siret_client" => NULL,
		"nom_client" => "Bazinet",
		"prenom_client" => "Jules",
		"nom_entreprise_client" => NULL,
	),
	array(
		"id" => 2,
		"categorie_client" => "Particulier",
		"adresse_livraison_client" => "4968 Marie Street",
		"cp_livraison_client" => "21217",
		"ville_livraison_client" => "Baltimore",
		"adresse_facture_client" => "4968 Marie Street",
		"cp_facture_client" => "21217",
		"ville_facture_client" => "Baltimore",
		"mode_paiement_client" => "CB",
		"reduction_client" => 1,
		"coefficient_client" => 1.05,
		"numero_siret_client" => NULL,
		"nom_client" => "Bureau",
		"prenom_client" => "Ray",
		"nom_entreprise_client" => NULL,
	),
	array(
		"id" => 3,
		"categorie_client" => "Particulier",
		"adresse_livraison_client" => "3083 Norma Lane",
		"cp_livraison_client" => "71201",
		"ville_livraison_client" => "Monroe",
		"adresse_facture_client" => "3083 Norma Lane",
		"cp_facture_client" => "71201",
		"ville_facture_client" => "Monroe",
		"mode_paiement_client" => "CB",
		"reduction_client" => 1,
		"coefficient_client" => 1.10,
		"numero_siret_client" => NULL,
		"nom_client" => "Meilleur",
		"prenom_client" => "Parnella",
		"nom_entreprise_client" => NULL,
	),
	array(
		"id" => 4,
		"categorie_client" => "Professionnel",
		"adresse_livraison_client" => "1292 Waterview Lane",
		"cp_livraison_client" => "88005",
		"ville_livraison_client" => "Las Cruces",
		"adresse_facture_client" => "2212 Neville Street",
		"cp_facture_client" => "47802",
		"ville_facture_client" => "Terre Haute",
		"mode_paiement_client" => "Virement/Chèque",
		"reduction_client" => 1,
		"coefficient_client" => 1.15,
		"numero_siret_client" => "12345678912345",
		"nom_client" => "Bouchard",
		"prenom_client" => "Percy",
		"nom_entreprise_client" => "Album ETC",
	),
	array(
		"id" => 5,
		"categorie_client" => "Professionnel",
		"adresse_livraison_client" => "1728 Meadowview Drive",
		"cp_livraison_client" => "22821",
		"ville_livraison_client" => "Dayton",
		"adresse_facture_client" => "1728 Meadowview Drive",
		"cp_facture_client" => "22821",
		"ville_facture_client" => "Dayton",
		"mode_paiement_client" => "Virement/Chèque",
		"reduction_client" => 1,
		"coefficient_client" => 1.10,
		"numero_siret_client" => "98765432109876",
		"nom_client" => "Faure",
		"prenom_client" => "Eustache",
		"nom_entreprise_client" => "Fantômes Jazzy",
	),
	array(
		"id" => 6,
		"categorie_client" => "Professionnel",
		"adresse_livraison_client" => "3570 County Line Road",
		"cp_livraison_client" => "33602",
		"ville_livraison_client" => "Tampa",
		"adresse_facture_client" => "2511 Mount Olive Road",
		"cp_facture_client" => "30501",
		"ville_facture_client" => "Gainesville",
		"mode_paiement_client" => "Virement/Chèque",
		"reduction_client" => 1.05,
		"coefficient_client" => 1.09,
		"numero_siret_client" => "36925814701234",
		"nom_client" => "Flamand",
		"prenom_client" => "William",
		"nom_entreprise_client" => "Mane 5",
	),
);
?>