<?php
$commandes = array(
	array(
		"id" => 1,
		"id_client_id" => 1,
		"date_commande" => "2022-05-17",
		"adresse_livraison_commande" => "39193 Lulu Way Apt. 696",
		"cp_livraison_commande" => "80287",
		"ville_livraison_commande" => "Baton Rouge",
		"adresse_facture_commande" => "39193 Lulu Way Apt. 696",
		"cp_facture_commande" => "80287",
		"ville_facture_commande" => "Baton Rouge",
		"date_facture" => "2022-05-17",
		"total_commande" => 12.45,
	),
	array(
		"id" => 2,
		"id_client_id" => 4,
		"date_commande" => "2022-05-17",
		"adresse_livraison_commande" => "1292 Waterview Lane",
		"cp_livraison_commande" => "88005",
		"ville_livraison_commande" => "Las Cruces",
		"adresse_facture_commande" => "2212 Neville Street",
		"cp_facture_commande" => "80287",
		"ville_facture_commande" => "Terre Haute",
		"date_facture" => "2022-05-26",
		"total_commande" => 0,
	),
	array(
		"id" => 3,
		"id_client_id" => 3,
		"date_commande" => "2022-05-17",
		"adresse_livraison_commande" => "3083 Norma Lane",
		"cp_livraison_commande" => "71201",
		"ville_livraison_commande" => "Monroe",
		"adresse_facture_commande" => "3083 Norma Lane",
		"cp_facture_commande" => "71201",
		"ville_facture_commande" => "Monroe",
		"date_facture" => "2022-05-17",
		"total_commande" => 0,
	),
	array(
		"id" => 4,
		"id_client_id" => 2,
		"date_commande" => "2022-05-17",
		"adresse_livraison_commande" => "4968 Marie Street",
		"cp_livraison_commande" => "21217",
		"ville_livraison_commande" => "Baltimore",
		"adresse_facture_commande" => "4968 Marie Street",
		"cp_facture_commande" => "21217",
		"ville_facture_commande" => "Baltimore",
		"date_facture" => "2022-05-17",
		"total_commande" => 0,
	),
	array(
		"id" => 5,
		"id_client_id" => 6,
		"date_commande" => "2022-04-03",
		"adresse_livraison_commande" => "3570 County Line Road",
		"cp_livraison_commande" => "33602",
		"ville_livraison_commande" => "Tampa",
		"adresse_facture_commande" => "2511 Mount Olive Road",
		"cp_facture_commande" => "30501",
		"ville_facture_commande" => "Gainesville",
		"date_facture" => "2022-06-03",
		"total_commande" => 0,
	),
	array(
		"id" => 6,
		"id_client_id" => 5,
		"date_commande" => "2022-04-03",
		"adresse_livraison_commande" => "1728 Meadowview Drive",
		"cp_livraison_commande" => "22821",
		"ville_livraison_commande" => "Dayton",
		"adresse_facture_commande" => "1728 Meadowview Drive",
		"cp_facture_commande" => "22821",
		"ville_facture_commande" => "Dayton",
		"date_facture" => "2022-05-17",
		"total_commande" => 0,
	),
);
?>